<a href="https://colab.research.google.com/github/manthribharadwaj12/AD/blob/master/Assignment_4_06_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CSE-221710313031-M S S BHARADWAJ

Question 1:

# [Reversing an Array] 

Write a NumPy program to reverse an array (first element becomes last). 

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


In [0]:
import numpy as np

In [0]:
a=np.arange(12,38)
b=a[::-1]
print("original array:",a)
print("reversed array:",b)

original array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
reversed array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


Question 2:

# [Make Border 1] 

Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

Original array:

[[ 1. 1. 1. 1. 1.]

...................

[ 1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array

Expected output:

[[ 1. 1. 1. 1. 1.]

[1. 0. 0. 0. 1.]

……………..

[1. 0. 0. 0. 1.]

[ 1. 1. 1. 1. 1.]]


In [0]:

a1=int(input())
a2=int(input())
b=np.ones((a1,a2),dtype="int32")
b[1:a1-1,1:a2-1]=0
b

4
4


array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

Question 3:

# [Membership Test] 

Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

Expected Output:

Array1: [ 0 10 20 40 60]

Array2: [0, 40]

Compare each element of array1 and array2

[ True False False True False]



In [0]:
a3=np.array([0,10,20,40,60])
a4=np.array([0,40])
r=[]
if(len(a3)>=len(a4)):
    for i in a3:
        r.append(i in a4)
else:
    for i in a4:
        r.append(i in a3)
r
    

[True, False, False, True, False]

Question 4:

# [Set Difference] 

Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

Expected Output:

Array1: [ 0 10 20 40 60 80]

Array2: [10, 30, 40, 50, 70, 90]

Set difference between two arrays:

[ 0 20 60 80]


In [0]:
ar1=np.array([0,10,20,40,60,80])
ar2=np.array([10,30,40,50,70,90])
r=[]
for i in ar1:
    if i not in ar2:
        r.append(i)
r.sort()
r

[0, 20, 60, 80]

Question 5:

# [Formation of Diagonal Matrix] 

Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.
Expected Output:
[[4 0 0 0]

[0 5 0 0]

[0 0 6 0]

[0 0 0 8]]


In [0]:
l=[4,5,6,8]
A=np.eye(len(l),dtype="int32")
for i in range(len(l)):
    A[i,i]=l[i]
A

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])